2019-01-25 16:53:19,862 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:48]
2019-01-25 19:17:44,284 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:50]
2019-01-25 19:17:59,080 ERROR: Exception on /login [GET] [in /home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/larsle/git/microblog/app/routes.py", line 49, in login
    return render_template("login.html", title="Sign In", form=form)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/larsle/git/microblog/app/templates/login.html", line 4, in template
    {% app_block content %}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'app_block'.
2019-01-25 19:21:44,707 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:50]
2019-01-25 19:22:18,147 ERROR: Exception on / [GET] [in /home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/larsle/git/microblog/app/routes.py", line 31, in index
    prev_url=prev_url)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/larsle/git/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/larsle/git/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/larsle/git/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/larsle/git/microblog/app/templates/index.html", line 14, in block "app_content"
    {% include "_post.html" %}
  File "/home/larsle/git/microblog/app/templates/_post.html", line 3, in top-level template code
    <td width="70px"><a href="{{ url_for('user', username.post.author.username) }}">
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'username' is undefined
